[versions]
kotlin          = "2.3.20"
compose         = "1.7.0"
ktor            = "3.0.3"
coroutines      = "1.9.0"
serialization   = "1.7.3"
sqldelight      = "2.3.2"
datetime        = "0.6.0"
coil            = "3.0.4"

[libraries]
kotlinx-datetime                   = { module = "org.jetbrains.kotlinx:kotlinx-datetime",              version.ref = "datetime" }
ktor-client-core                   = { module = "io.ktor:ktor-client-core",                        version.ref = "ktor" }
ktor-client-darwin                 = { module = "io.ktor:ktor-client-darwin",                      version.ref = "ktor" }
ktor-client-auth                   = { module = "io.ktor:ktor-client-auth",                        version.ref = "ktor" }
ktor-client-content-negotiation    = { module = "io.ktor:ktor-client-content-negotiation",         version.ref = "ktor" }
ktor-serialization-kotlinx-json    = { module = "io.ktor:ktor-serialization-kotlinx-json",         version.ref = "ktor" }
kotlinx-coroutines-core            = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core",   version.ref = "coroutines" }
kotlinx-serialization-json         = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json",version.ref = "serialization" }
sqldelight-runtime                 = { module = "app.cash.sqldelight:runtime",                     version.ref = "sqldelight" }
sqldelight-coroutines-extensions   = { module = "app.cash.sqldelight:coroutines-extensions",       version.ref = "sqldelight" }
sqldelight-native-driver           = { module = "app.cash.sqldelight:native-driver",               version.ref = "sqldelight" }
coil-compose                       = { module = "io.coil-kt.coil3:coil-compose",                    version.ref = "coil" }
coil-network-ktor                  = { module = "io.coil-kt.coil3:coil-network-ktor3",              version.ref = "coil" }

[plugins]
kotlinMultiplatform  = { id = "org.jetbrains.kotlin.multiplatform",          version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose",                        version.ref = "compose" }
composeCompiler      = { id = "org.jetbrains.kotlin.plugin.compose",          version.ref = "kotlin" }
kotlinSerialization  = { id = "org.jetbrains.kotlin.plugin.serialization",    version.ref = "kotlin" }
sqldelight           = { id = "app.cash.sqldelight",                          version.ref = "sqldelight" }
