package org.gipsybuho.recetasfamiliares.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp

private val LightError = Color(0xFFBA1A1A)
private val LightOnError = Color(0xFFFFFFFF)
private val LightErrorContainer = Color(0xFFFFDAD6)
private val LightOnErrorContainer = Color(0xFF410002)
private val DarkError = Color(0xFFFFB4AB)
private val DarkOnError = Color(0xFF690005)
private val DarkErrorContainer = Color(0xFF93000A)
private val DarkOnErrorContainer = Color(0xFFFFDAD6)

private fun premiumLightColorScheme(
    primary: Color,
    onPrimary: Color,
    primaryContainer: Color,
    onPrimaryContainer: Color,
    inversePrimary: Color,
    secondary: Color,
    onSecondary: Color,
    secondaryContainer: Color,
    onSecondaryContainer: Color,
    tertiary: Color,
    onTertiary: Color,
    tertiaryContainer: Color,
    onTertiaryContainer: Color,
    background: Color,
    onBackground: Color,
    surface: Color,
    onSurface: Color,
    surfaceVariant: Color,
    onSurfaceVariant: Color,
    outline: Color,
): ColorScheme = lightColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    inversePrimary = inversePrimary,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    surfaceTint = primary,
    inverseSurface = onSurface,
    inverseOnSurface = surface,
    error = LightError,
    onError = LightOnError,
    errorContainer = LightErrorContainer,
    onErrorContainer = LightOnErrorContainer,
    outline = outline,
    outlineVariant = lerp(surfaceVariant, outline, 0.30f),
    scrim = Color.Black,
    surfaceBright = surface,
    surfaceDim = lerp(surfaceVariant, surface, 0.28f),
    surfaceContainerLowest = surface,
    surfaceContainerLow = lerp(surface, surfaceVariant, 0.18f),
    surfaceContainer = lerp(surface, surfaceVariant, 0.34f),
    surfaceContainerHigh = lerp(surface, surfaceVariant, 0.52f),
    surfaceContainerHighest = lerp(surface, surfaceVariant, 0.70f),
    primaryFixed = primaryContainer,
    primaryFixedDim = lerp(primaryContainer, primary, 0.18f),
    onPrimaryFixed = onPrimaryContainer,
    onPrimaryFixedVariant = onPrimaryContainer,
    secondaryFixed = secondaryContainer,
    secondaryFixedDim = lerp(secondaryContainer, secondary, 0.18f),
    onSecondaryFixed = onSecondaryContainer,
    onSecondaryFixedVariant = onSecondaryContainer,
    tertiaryFixed = tertiaryContainer,
    tertiaryFixedDim = lerp(tertiaryContainer, tertiary, 0.18f),
    onTertiaryFixed = onTertiaryContainer,
    onTertiaryFixedVariant = onTertiaryContainer,
)

private fun premiumDarkColorScheme(
    primary: Color,
    onPrimary: Color,
    primaryContainer: Color,
    onPrimaryContainer: Color,
    inversePrimary: Color,
    secondary: Color,
    onSecondary: Color,
    secondaryContainer: Color,
    onSecondaryContainer: Color,
    tertiary: Color,
    onTertiary: Color,
    tertiaryContainer: Color,
    onTertiaryContainer: Color,
    background: Color,
    onBackground: Color,
    surface: Color,
    onSurface: Color,
    surfaceVariant: Color,
    onSurfaceVariant: Color,
    outline: Color,
): ColorScheme = darkColorScheme(
    primary = primary,
    onPrimary = onPrimary,
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    inversePrimary = inversePrimary,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    tertiary = tertiary,
    onTertiary = onTertiary,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceVariant,
    onSurfaceVariant = onSurfaceVariant,
    surfaceTint = primary,
    inverseSurface = onSurface,
    inverseOnSurface = background,
    error = DarkError,
    onError = DarkOnError,
    errorContainer = DarkErrorContainer,
    onErrorContainer = DarkOnErrorContainer,
    outline = outline,
    outlineVariant = lerp(surfaceVariant, outline, 0.30f),
    scrim = Color.Black,
    surfaceBright = lerp(surface, surfaceVariant, 0.76f),
    surfaceDim = background,
    surfaceContainerLowest = background,
    surfaceContainerLow = lerp(surface, surfaceVariant, 0.14f),
    surfaceContainer = lerp(surface, surfaceVariant, 0.28f),
    surfaceContainerHigh = lerp(surface, surfaceVariant, 0.46f),
    surfaceContainerHighest = lerp(surface, surfaceVariant, 0.64f),
    primaryFixed = onPrimaryContainer,
    primaryFixedDim = primary,
    onPrimaryFixed = onPrimary,
    onPrimaryFixedVariant = onPrimary,
    secondaryFixed = onSecondaryContainer,
    secondaryFixedDim = secondary,
    onSecondaryFixed = onSecondary,
    onSecondaryFixedVariant = onSecondary,
    tertiaryFixed = onTertiaryContainer,
    tertiaryFixedDim = tertiary,
    onTertiaryFixed = onTertiary,
    onTertiaryFixedVariant = onTertiary,
)

internal fun rubiNocturnoLightColors(): ColorScheme = premiumLightColorScheme(
    primary = Color(0xFF8F1236), onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E2), onPrimaryContainer = Color(0xFF3F0014),
    inversePrimary = Color(0xFFFF9EB4),
    secondary = Color(0xFF6A4D57), onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9E2), onSecondaryContainer = Color(0xFF2B151D),
    tertiary = Color(0xFF80542C), onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDCBA), onTertiaryContainer = Color(0xFF2E1600),
    background = Color(0xFFFFF8F8), onBackground = Color(0xFF211A1C),
    surface = Color(0xFFFFF8F8), onSurface = Color(0xFF211A1C),
    surfaceVariant = Color(0xFFF2DDE2), onSurfaceVariant = Color(0xFF514347),
    outline = Color(0xFF847176),
)

internal fun rubiNocturnoDarkColors(): ColorScheme = premiumDarkColorScheme(
    primary = Color(0xFFFF9EB4), onPrimary = Color(0xFF5F0024),
    primaryContainer = Color(0xFF850032), onPrimaryContainer = Color(0xFFFFD9E2),
    inversePrimary = Color(0xFF8F1236),
    secondary = Color(0xFFE1BEC7), onSecondary = Color(0xFF402932),
    secondaryContainer = Color(0xFF59404A), onSecondaryContainer = Color(0xFFFFD9E2),
    tertiary = Color(0xFFF0BD8A), onTertiary = Color(0xFF452B08),
    tertiaryContainer = Color(0xFF60411E), onTertiaryContainer = Color(0xFFFFDCBA),
    background = Color(0xFF100A0D), onBackground = Color(0xFFF0DEE3),
    surface = Color(0xFF190E13), onSurface = Color(0xFFF0DEE3),
    surfaceVariant = Color(0xFF49323A), onSurfaceVariant = Color(0xFFD6C0C6),
    outline = Color(0xFFA18A91),
)

internal fun auroraBorealLightColors(): ColorScheme = premiumLightColorScheme(
    primary = Color(0xFF3555A5), onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDCE1FF), onPrimaryContainer = Color(0xFF00164D),
    inversePrimary = Color(0xFFB8C4FF),
    secondary = Color(0xFF006B62), onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF75F8E6), onSecondaryContainer = Color(0xFF00201D),
    tertiary = Color(0xFF77558E), onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF3DAFF), onTertiaryContainer = Color(0xFF2E0D46),
    background = Color(0xFFFAF8FF), onBackground = Color(0xFF1B1B23),
    surface = Color(0xFFFAF8FF), onSurface = Color(0xFF1B1B23),
    surfaceVariant = Color(0xFFE4E1EE), onSurfaceVariant = Color(0xFF46464F),
    outline = Color(0xFF777681),
)

internal fun auroraBorealDarkColors(): ColorScheme = premiumDarkColorScheme(
    primary = Color(0xFFB8C4FF), onPrimary = Color(0xFF002B72),
    primaryContainer = Color(0xFF1E438C), onPrimaryContainer = Color(0xFFDCE1FF),
    inversePrimary = Color(0xFF3555A5),
    secondary = Color(0xFF5DDBCD), onSecondary = Color(0xFF003733),
    secondaryContainer = Color(0xFF005048), onSecondaryContainer = Color(0xFF75F8E6),
    tertiary = Color(0xFFDFB7F5), onTertiary = Color(0xFF452455),
    tertiaryContainer = Color(0xFF5D3B6C), onTertiaryContainer = Color(0xFFF3DAFF),
    background = Color(0xFF0C1020), onBackground = Color(0xFFE4E1ED),
    surface = Color(0xFF14182A), onSurface = Color(0xFFE4E1ED),
    surfaceVariant = Color(0xFF383D52), onSurfaceVariant = Color(0xFFC3C5D4),
    outline = Color(0xFF8D91A4),
)

internal fun jadeImperialLightColors(): ColorScheme = premiumLightColorScheme(
    primary = Color(0xFF006B52), onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF8DF8D1), onPrimaryContainer = Color(0xFF002117),
    inversePrimary = Color(0xFF70DBB5),
    secondary = Color(0xFF5A622B), onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDFE9A2), onSecondaryContainer = Color(0xFF191E00),
    tertiary = Color(0xFF8A4E23), onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDBC7), onTertiaryContainer = Color(0xFF351000),
    background = Color(0xFFF5FBF6), onBackground = Color(0xFF171D1A),
    surface = Color(0xFFF5FBF6), onSurface = Color(0xFF171D1A),
    surfaceVariant = Color(0xFFDCE8E1), onSurfaceVariant = Color(0xFF3F4944),
    outline = Color(0xFF6F7974),
)

internal fun jadeImperialDarkColors(): ColorScheme = premiumDarkColorScheme(
    primary = Color(0xFF70DBB5), onPrimary = Color(0xFF00382A),
    primaryContainer = Color(0xFF00513E), onPrimaryContainer = Color(0xFF8DF8D1),
    inversePrimary = Color(0xFF006B52),
    secondary = Color(0xFFC5CE88), onSecondary = Color(0xFF2E3500),
    secondaryContainer = Color(0xFF444C13), onSecondaryContainer = Color(0xFFDFE9A2),
    tertiary = Color(0xFFFFB68B), onTertiary = Color(0xFF512100),
    tertiaryContainer = Color(0xFF71360F), onTertiaryContainer = Color(0xFFFFDBC7),
    background = Color(0xFF091713), onBackground = Color(0xFFDCE5DF),
    surface = Color(0xFF111F1B), onSurface = Color(0xFFDCE5DF),
    surfaceVariant = Color(0xFF344943), onSurfaceVariant = Color(0xFFBAC9C1),
    outline = Color(0xFF84978E),
)

internal fun cobreLunarLightColors(): ColorScheme = premiumLightColorScheme(
    primary = Color(0xFF8B4A1A), onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCC3), onPrimaryContainer = Color(0xFF321200),
    inversePrimary = Color(0xFFFFB783),
    secondary = Color(0xFF555D72), onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDCE2FA), onSecondaryContainer = Color(0xFF121A2C),
    tertiary = Color(0xFF6D568C), onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFECDDFB), onTertiaryContainer = Color(0xFF27133F),
    background = Color(0xFFFFF8F4), onBackground = Color(0xFF211A16),
    surface = Color(0xFFFFF8F4), onSurface = Color(0xFF211A16),
    surfaceVariant = Color(0xFFECE0D8), onSurfaceVariant = Color(0xFF4D453F),
    outline = Color(0xFF7F746C),
)

internal fun cobreLunarDarkColors(): ColorScheme = premiumDarkColorScheme(
    primary = Color(0xFFFFB783), onPrimary = Color(0xFF522300),
    primaryContainer = Color(0xFF723600), onPrimaryContainer = Color(0xFFFFDCC3),
    inversePrimary = Color(0xFF8B4A1A),
    secondary = Color(0xFFBEC6DC), onSecondary = Color(0xFF283044),
    secondaryContainer = Color(0xFF3E475C), onSecondaryContainer = Color(0xFFDCE2FA),
    tertiary = Color(0xFFD7BDF7), onTertiary = Color(0xFF3D275C),
    tertiaryContainer = Color(0xFF554074), onTertiaryContainer = Color(0xFFECDDFB),
    background = Color(0xFF111319), onBackground = Color(0xFFE2E2EA),
    surface = Color(0xFF191C23), onSurface = Color(0xFFE2E2EA),
    surfaceVariant = Color(0xFF40444F), onSurfaceVariant = Color(0xFFC4C6D0),
    outline = Color(0xFF90939F),
)

internal fun ciruelaSolarLightColors(): ColorScheme = premiumLightColorScheme(
    primary = Color(0xFF7B2B64), onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD7EE), onPrimaryContainer = Color(0xFF31002A),
    inversePrimary = Color(0xFFF4AFDB),
    secondary = Color(0xFF8A4F00), onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDCB4), onSecondaryContainer = Color(0xFF2C1600),
    tertiary = Color(0xFF575B91), onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE0E1FF), onTertiaryContainer = Color(0xFF121747),
    background = Color(0xFFFFF7FC), onBackground = Color(0xFF20191F),
    surface = Color(0xFFFFF7FC), onSurface = Color(0xFF20191F),
    surfaceVariant = Color(0xFFEEDFE8), onSurfaceVariant = Color(0xFF50434B),
    outline = Color(0xFF82727D),
)

internal fun ciruelaSolarDarkColors(): ColorScheme = premiumDarkColorScheme(
    primary = Color(0xFFF4AFDB), onPrimary = Color(0xFF4B043E),
    primaryContainer = Color(0xFF66214F), onPrimaryContainer = Color(0xFFFFD7EE),
    inversePrimary = Color(0xFF7B2B64),
    secondary = Color(0xFFFFB865), onSecondary = Color(0xFF4A2800),
    secondaryContainer = Color(0xFF693B00), onSecondaryContainer = Color(0xFFFFDCB4),
    tertiary = Color(0xFFC1C4FF), onTertiary = Color(0xFF2B2F62),
    tertiaryContainer = Color(0xFF444779), onTertiaryContainer = Color(0xFFE0E1FF),
    background = Color(0xFF180E17), onBackground = Color(0xFFEADFE8),
    surface = Color(0xFF211520), onSurface = Color(0xFFEADFE8),
    surfaceVariant = Color(0xFF4E3A4C), onSurfaceVariant = Color(0xFFD2C0CE),
    outline = Color(0xFF9B8796),
)

internal fun coralAbisalLightColors(): ColorScheme = premiumLightColorScheme(
    primary = Color(0xFF006875), onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF97F0FF), onPrimaryContainer = Color(0xFF001F24),
    inversePrimary = Color(0xFF4FD8E9),
    secondary = Color(0xFF9B4047), onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDADB), onSecondaryContainer = Color(0xFF40000A),
    tertiary = Color(0xFF6E5D00), onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF7E47B), onTertiaryContainer = Color(0xFF211B00),
    background = Color(0xFFF5FAFC), onBackground = Color(0xFF171C1E),
    surface = Color(0xFFF5FAFC), onSurface = Color(0xFF171C1E),
    surfaceVariant = Color(0xFFDAE7EA), onSurfaceVariant = Color(0xFF3F494C),
    outline = Color(0xFF6F7A7E),
)

internal fun coralAbisalDarkColors(): ColorScheme = premiumDarkColorScheme(
    primary = Color(0xFF4FD8E9), onPrimary = Color(0xFF00363D),
    primaryContainer = Color(0xFF004F59), onPrimaryContainer = Color(0xFF97F0FF),
    inversePrimary = Color(0xFF006875),
    secondary = Color(0xFFFFB3B5), onSecondary = Color(0xFF5F121A),
    secondaryContainer = Color(0xFF812933), onSecondaryContainer = Color(0xFFFFDADB),
    tertiary = Color(0xFFDBC65E), onTertiary = Color(0xFF393000),
    tertiaryContainer = Color(0xFF514700), onTertiaryContainer = Color(0xFFF7E47B),
    background = Color(0xFF06161A), onBackground = Color(0xFFDDE4E6),
    surface = Color(0xFF0E2024), onSurface = Color(0xFFDDE4E6),
    surfaceVariant = Color(0xFF30494E), onSurfaceVariant = Color(0xFFB6CACE),
    outline = Color(0xFF82999E),
)
